language: r
cache: packages
sudo: false

env:
  - NOT_CRAN=true

addons:
  apt:
    packages:
      - libgsl0-dev

before_script:
  - Rscript -e 'Rcpp::compileAttributes(Sys.getenv("TRAVIS_BUILD_DIR"))'

after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'

r-packages:

r_binary_packages:
  - gsl

