language: r
cache: packages
sudo: false

addons:
  apt:
    packages:
- libgsl0-dev

before_script:
  - Rscript -e 'Rcpp::compileAttributes()'

after_success:
  - Rscript -e 'covr::codecov()'

r-packages:

r_binary_packages:
  - gsl

