language: r
cache: packages
sudo: false

env:
  - NOT_CRAN=true

addons:
  apt:
    packages:
      - libgsl0-dev

os:
  - linux
  - osx

r:
  - release
  - devel

before_script:
  - Rscript -e 'Rcpp::compileAttributes(Sys.getenv("TRAVIS_BUILD_DIR"))'

after_success:
  - travis_wait 30 if [[ "$TRAVIS_R_VERSION" != "release" && ("$TRAVIS_OS_NAME" == "linux") ]]; then Rscript -e 'covr::codecov()'; fi

r-packages:

r_binary_packages:
  - gsl

