language: r
cache: packages
sudo: false

env:
  - NOT_CRAN=true

addons:
  apt:
    packages:
      - libgsl0-dev
os:
  - linux
  - osx

r:
  - release
  - devel

env:
  - DO_CODECOV=true
  - DO_CODECOV=false

matrix:
  exclude:
    - os: linux
      r: release
      env: DO_CODECOV=false
    - os: osx
      env: DO_CODECOV=true
    - r: devel
      env: DO_CODECOV=true

before_script:
  - Rscript -e 'Rcpp::compileAttributes(Sys.getenv("TRAVIS_BUILD_DIR"))'

after_success:
  - if [[ "$DO_CODECOV" == "true" ]]; then travis_wait 30 Rscript -e 'covr::codecov()'; fi

