language: r
cache: packages
sudo: false

env:
  global:
    - NOT_CRAN=true
  matrix:
    - DO_CODECOV=true
    - DO_CODECOV=false

addons:
  apt:
    packages:
      - libgsl0-dev
os:
  - linux
  - osx

r:
  - release
  - devel

matrix:
  exclude:
    - os: linux
      r: release
      env: DO_CODECOV=false
    - os: osx
      env: DO_CODECOV=true
    - r: devel
      env: DO_CODECOV=true
  allow_failures:
    - os: osx
      r: devel

branches:
  only: 
    - master

r_github_packages: kevinushey/sourcetools

before_script:
  - Rscript -e 'Rcpp::compileAttributes(Sys.getenv("TRAVIS_BUILD_DIR")); sourcetools:::register_routines()'

after_success:
  - if [[ "$DO_CODECOV" == "true" ]]; then travis_wait 30 Rscript -e 'covr::codecov()'; fi

