language: r
cache: packages
sudo: false

addons:
  apt:
    packages:
      - libgsl0-dev

before_install:
  - Rscript -e 'Rcpp::compileAttributes()'

after_success:
  - Rscript -e 'covr::codecov()'

r-packages:
  - covr

r_binary_packages:
  - gsl

