// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// VI
Rcpp::List VI(arma::mat Udata, arma::mat Wdata, double NumbBoot);
RcppExport SEXP SAtest_VI(SEXP UdataSEXP, SEXP WdataSEXP, SEXP NumbBootSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Udata(UdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wdata(WdataSEXP);
    Rcpp::traits::input_parameter< double >::type NumbBoot(NumbBootSEXP);
    __result = Rcpp::wrap(VI(Udata, Wdata, NumbBoot));
    return __result;
END_RCPP
}
// ERC
Rcpp::List ERC(arma::mat Udata, arma::mat Wdata, double Grouping, double AggPvalsNumbRep, double ExpMinSampleSize, double TrainingDataFraction);
RcppExport SEXP SAtest_ERC(SEXP UdataSEXP, SEXP WdataSEXP, SEXP GroupingSEXP, SEXP AggPvalsNumbRepSEXP, SEXP ExpMinSampleSizeSEXP, SEXP TrainingDataFractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Udata(UdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wdata(WdataSEXP);
    Rcpp::traits::input_parameter< double >::type Grouping(GroupingSEXP);
    Rcpp::traits::input_parameter< double >::type AggPvalsNumbRep(AggPvalsNumbRepSEXP);
    Rcpp::traits::input_parameter< double >::type ExpMinSampleSize(ExpMinSampleSizeSEXP);
    Rcpp::traits::input_parameter< double >::type TrainingDataFraction(TrainingDataFractionSEXP);
    __result = Rcpp::wrap(ERC(Udata, Wdata, Grouping, AggPvalsNumbRep, ExpMinSampleSize, TrainingDataFraction));
    return __result;
END_RCPP
}
// EC
Rcpp::List EC(arma::mat Udata, arma::mat Wdata, double NumbBoot, double Grouping, double ExpMinSampleSize, double TrainingDataFraction);
RcppExport SEXP SAtest_EC(SEXP UdataSEXP, SEXP WdataSEXP, SEXP NumbBootSEXP, SEXP GroupingSEXP, SEXP ExpMinSampleSizeSEXP, SEXP TrainingDataFractionSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type Udata(UdataSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Wdata(WdataSEXP);
    Rcpp::traits::input_parameter< double >::type NumbBoot(NumbBootSEXP);
    Rcpp::traits::input_parameter< double >::type Grouping(GroupingSEXP);
    Rcpp::traits::input_parameter< double >::type ExpMinSampleSize(ExpMinSampleSizeSEXP);
    Rcpp::traits::input_parameter< double >::type TrainingDataFraction(TrainingDataFractionSEXP);
    __result = Rcpp::wrap(EC(Udata, Wdata, NumbBoot, Grouping, ExpMinSampleSize, TrainingDataFraction));
    return __result;
END_RCPP
}
