# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VI <- function(Udata, Wdata, NumbBoot) {
    .Call('pacotest_VI', PACKAGE = 'pacotest', Udata, Wdata, NumbBoot)
}

EC <- function(Udata, Wdata, NumbBoot, Grouping, finalComparison, ExpMinSampleSize = 50, TrainingDataFraction = 0.5) {
    .Call('pacotest_EC', PACKAGE = 'pacotest', Udata, Wdata, NumbBoot, Grouping, finalComparison, ExpMinSampleSize, TrainingDataFraction)
}

ECOV <- function(Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep = 0, ExpMinSampleSize = 50, TrainingDataFraction = 0.5) {
    .Call('pacotest_ECOV', PACKAGE = 'pacotest', Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep, ExpMinSampleSize, TrainingDataFraction)
}

ERC <- function(Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep = 0, ExpMinSampleSize = 50, TrainingDataFraction = 0.5) {
    .Call('pacotest_ERC', PACKAGE = 'pacotest', Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep, ExpMinSampleSize, TrainingDataFraction)
}

ECOVold <- function(Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep = 0, ExpMinSampleSize = 50, TrainingDataFraction = 0.5) {
    .Call('pacotest_ECOVold', PACKAGE = 'pacotest', Udata, Wdata, Grouping, doubleWithEstUncert, finalComparison, data, svcmDataFrame, cPitData, AggPvalsNumbRep, ExpMinSampleSize, TrainingDataFraction)
}

testStatEqualCorrWithEstimationFromCpp <- function(data, svcmDataFrame, ind, out) {
    .Call('pacotest_testStatEqualCorrWithEstimationFromCpp', PACKAGE = 'pacotest', data, svcmDataFrame, ind, out)
}

covOfCorrelationsWithEstimationFromCpp <- function(data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma) {
    .Call('pacotest_covOfCorrelationsWithEstimationFromCpp', PACKAGE = 'pacotest', data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma)
}

covOfCovariancesWithEstimationFromCpp <- function(data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma) {
    .Call('pacotest_covOfCovariancesWithEstimationFromCpp', PACKAGE = 'pacotest', data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma)
}

testStatEqualCorrWithoutEstimationCpp <- function(ind, Udata) {
    .Call('pacotest_testStatEqualCorrWithoutEstimationCpp', PACKAGE = 'pacotest', ind, Udata)
}

testStatEqualCorrWithEstimationCpp <- function(ind, Udata, data, svcmDataFrame, cPitData) {
    .Call('pacotest_testStatEqualCorrWithEstimationCpp', PACKAGE = 'pacotest', ind, Udata, data, svcmDataFrame, cPitData)
}

