# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VI <- function(Udata, Wdata, NumbBoot) {
    .Call('SAtest_VI', PACKAGE = 'SAtest', Udata, Wdata, NumbBoot)
}

ERC <- function(Udata, Wdata, Grouping, AggPvalsNumbRep = 0, ExpMinSampleSize = 50, EvaluationDataFraction = 0.5) {
    .Call('SAtest_ERC', PACKAGE = 'SAtest', Udata, Wdata, Grouping, AggPvalsNumbRep, ExpMinSampleSize, EvaluationDataFraction)
}

EC <- function(Udata, Wdata, NumbBoot, Grouping, ExpMinSampleSize = 50, EvaluationDataFraction = 0.5) {
    .Call('SAtest_EC', PACKAGE = 'SAtest', Udata, Wdata, NumbBoot, Grouping, ExpMinSampleSize, EvaluationDataFraction)
}

