# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

VI <- function(Udata, Wdata, NumbBoot) {
    .Call('_pacotest_VI', PACKAGE = 'pacotest', Udata, Wdata, NumbBoot)
}

EC <- function(Udata, Wdata, NumbBoot, Grouping, finalComparison, ExpMinSampleSize = 50) {
    .Call('_pacotest_EC', PACKAGE = 'pacotest', Udata, Wdata, NumbBoot, Grouping, finalComparison, ExpMinSampleSize)
}

CCC <- function(Udata, Wdata, doubleDimCondSet, Grouping, doubleWithEstUncert, doubleEstUncertWithRanks, finalComparison, data, svcmDataFrame, cPitData, ExpMinSampleSize = NA_real_, penaltyLevel = NA_real_, penaltyPower = NA_real_, Gamma0Partition = NA_real_) {
    .Call('_pacotest_CCC', PACKAGE = 'pacotest', Udata, Wdata, doubleDimCondSet, Grouping, doubleWithEstUncert, doubleEstUncertWithRanks, finalComparison, data, svcmDataFrame, cPitData, ExpMinSampleSize, penaltyLevel, penaltyPower, Gamma0Partition)
}

covOfCorrelationsWithEstimationFromCpp <- function(data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma, intEstUncertWithRanks) {
    invisible(.Call('_pacotest_covOfCorrelationsWithEstimationFromCpp', PACKAGE = 'pacotest', data, svcmDataFrame, indexVectors, nObsPerVector, cPitData, theta, sigma, intEstUncertWithRanks))
}

testStatEqualCorrWithoutEstimationCpp <- function(indexVectors, nObsPerVector, Udata) {
    .Call('_pacotest_testStatEqualCorrWithoutEstimationCpp', PACKAGE = 'pacotest', indexVectors, nObsPerVector, Udata)
}

testStatEqualCorrWithEstimationCpp <- function(indexVectors, nObsPerVector, Udata, data, svcmDataFrame, cPitData) {
    .Call('_pacotest_testStatEqualCorrWithEstimationCpp', PACKAGE = 'pacotest', indexVectors, nObsPerVector, Udata, data, svcmDataFrame, cPitData)
}

